name: Fetch and Upload 511 Alerts

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch 511 Alerts and Convert to GeoJSON
        run: python fetch_511_data.py

      - name: List files
        run: ls -la

      - name: Commit GeoJSON file
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add alerts.geojson
          git commit -m 'Add GeoJSON file'
          git push
